employee_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('master.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

master/urls.py
from django.urls import path
from . import views



urlpatterns = [

    #--------------------------- Dashboard URL -----------------------------------------------------------------------
    path('',views.user_login,name="user_login"),
    path('index',views.indexpage,name="indexpage"),
    path('admin_logout',views.admin_logout,name="admin_logout"),

    path('dashboard/', views.dashboard, name='dashboard'),
    
    #-------------------------- URLS OF DEPARTMENT------------------------------------------------------------------

    path('department_list/', views.department_list, name='department_list'),
    path('department_add/', views.department_add, name='department_add'),
    path('department_edit/<int:department_id>/', views.department_edit, name='department_edit'),
    path('department_view/<int:department_id>/', views.department_view, name='department_view'),
    path('department_delete/<int:department_id>/', views.department_delete, name='department_delete'),
    path('download_template/', views.download_template, name='download_template'),
    path('bulk_upload/', views.bulk_upload, name='bulk_upload'),
    path('export_departments/', views.export_departments, name='export_departments'),

    
    #-------------------------- URLS OF DESIGNATION------------------------------------------------------------------

    path('designation_list/', views.designation_list, name='designation_list'),
    path('designation_add/', views.designation_add, name='designation_add'),
    path('designation_edit/<int:designation_id>/', views.designation_edit, name='designation_edit'),
    path('designation_view/<int:designation_id>/', views.designation_view, name='designation_view'),
    path('designation_delete/<int:designation_id>/', views.designation_delete, name='designation_delete'),
    path('designation_download_template/', views.designation_download_template, name='designation_download_template'),
    path('designation_bulk_upload/', views.designation_bulk_upload, name='designation_bulk_upload'),
    path('export_designations/', views.export_designations, name='export_designations'),

    #-------------------------- URLS OF LOCATIONS------------------------------------------------------------------

    path('location_list/', views.location_list, name='location_list'),
    path('location_add/', views.location_add, name='location_add'),
    path('location_edit/<int:location_id>/', views.location_edit, name='location_edit'),
    path('location_view/<int:location_id>/', views.location_view, name='location_view'),
    path('location_delete/<int:location_id>/', views.location_delete, name='location_delete'),
    path('download_location_template/', views.download_location_template, name='download_location_template'),
    path('location_bulk_upload/', views.location_bulk_upload, name='location_bulk_upload'),
    path('export_locations/', views.export_locations, name='export_locations'),

    #-------------------------- URLS OF EMPLOYEE------------------------------------------------------------------

    path('employee_list', views.employee_list, name='employee_list'),
    path('employee_add', views.employee_add, name='employee_add'),
    path('designations_of_department', views.designations_of_department, name='designations_of_department'),
    path('employee_edit/<str:employee_id>/', views.employee_edit, name='employee_edit'),
    path('employee_view/<str:employee_id>/', views.employee_view, name='employee_view'),
    path('employee_delete/<str:employee_id>/', views.employee_delete, name='employee_delete'),
    path('export_employee/',views.export_employee, name='export_employee'),
    path('download_employee_template/', views.download_employee_template, name='download_employee_template'),
    path('bulk_upload_employees/', views.bulk_upload_employees, name='bulk_upload_employees'),
    path('filtered_employees/', views.filtered_employees, name='filtered_employees'),
    path('export_selected_employees/', views.export_selected_employees, name='export_selected_employees'),
    path('employee_pdf_download/<str:employee_id>/', views.employee_pdf_download, name='employee_pdf_download'),
    path('mail_pdf/<str:employee_id>/', views.mail_pdf, name='mail_pdf'),
#------------------------------------------ ACCOUNTS -------------------------------------------------------------------

    path('user_login', views.user_login, name='user_login'),
    path('user_list', views.user_list, name='user_list'),
    path('user_add', views.user_add, name='user_add'),
    path('user_edit/<str:id>/', views.user_edit, name='user_edit'),
    path('user_view/<str:id>/', views.user_view, name='user_view'),
    path('user_delete/<str:id>/', views.user_delete, name='user_delete'),
    path('download_user_template/', views.download_user_template, name='download_user_template'),
    path('user_bulk_upload/', views.user_bulk_upload, name='user_bulk_upload'),
    path('export_user_details/',views.export_user_details, name='export_user_details'),
    path('edit_profile/',views.edit_profile, name='edit_profile'),
    

]

master/models.py
from django.db import models
import uuid


# master/models.py

from django.db import models
from django.conf import settings
from django.utils import timezone


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='%(class)s_created_by',
        null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)  # Automatically updates on save
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,related_name='%(class)s_updated_by',blank=True, null=True)
    
    class Meta:
        abstract = True
#--------------------------------------------models for master ------------------------------------------------------------
class Department(TimeStampedModel):
    department_id = models.AutoField(primary_key=True)
    department_name = models.CharField(max_length=100)
    description = models.TextField()
    
    class Meta:
        db_table = 'department'

    def __str__(self):
        return str(self.department_name) 


class Designation(TimeStampedModel):
    designation_id = models.AutoField(primary_key=True)
    department = models.ForeignKey(Department,  on_delete=models.PROTECT,)
    designation_name = models.CharField(max_length=100)
    description =  models.TextField()

    class Meta:
        db_table = 'designation'
    def __str__(self):
        return str(self.designation_name) 
    
class Location(TimeStampedModel):
    location_id = models.AutoField(primary_key=True)
    location_name = models.CharField(max_length=100)
    description = models.TextField()
    
    class Meta:
        db_table = 'location'

    def __str__(self):
        return str(self.location_name) 


class Employee(TimeStampedModel):
    employee_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    join_date = models.DateField(null=True, blank=True)
    employee_no = models.IntegerField(null=True, blank=True)
    name = models.CharField(max_length=255,null=True, blank=True)
    phone = models.CharField(max_length=255,null=True, blank=True)
    address = models.CharField(max_length=255,null=True, blank=True)
    emp_start_date = models.DateField(null=True, blank=True)
    emp_end_date = models.DateField(null=True, blank=True)
    photo = models.ImageField(upload_to='employee_photos/', null=True, blank=True)
    status = models.CharField(max_length=50)
    department = models.ForeignKey(Department, max_length=250, null=True, blank=True, related_name='emp_dep',
                             on_delete=models.SET_NULL)
    designation = models.ForeignKey(Designation, max_length=250, null=True, blank=True, related_name='emp_des',
                             on_delete=models.SET_NULL)
    location = models.ForeignKey(Location, max_length=250, null=True, blank=True, related_name='emp_loc',
                             on_delete=models.SET_NULL)
    
    class Meta:
        db_table = 'employee'
    def __str__(self):
        return str(self.name)    
    

class Skills(models.Model):
    skill_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    employee = models.ForeignKey(Employee, related_name='skills', on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=100,null=True, blank=True)
    description = models.CharField(max_length=255,null=True, blank=True)

    class Meta:
        db_table = 'skills'
    def __str__(self):
        return str(self.skill_name)   
    



from django.contrib.auth.models import User,AbstractUser, Group, Permission

class User(AbstractUser):
    ROLE_TYPES = (
        ('ADMIN', 'ADMIN'),
        ('VIEWER', 'VIEWER'),
    )

    role = models.CharField(max_length=10, choices=ROLE_TYPES)

    groups = models.ManyToManyField(
        Group,
        related_name='custom_user_groups' 
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name='custom_user_permissions' 
    )

    def get_instance(self):
        return self

templates/department-edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <title>KWARTZ</title>
    <meta name="robots" content="noindex, nofollow" />
    <meta content="" name="description" />
    <meta content="" name="keywords" />
    <link href="{% static 'img/favicon.png' %}" rel="icon" />

    <!-- Google Fonts Nunito & Poppins -->
    <link href="https://fonts.gstatic.com" rel="preconnect" />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />
    <!-- select2 -->
    <link
      href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
      rel="stylesheet"
    />

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Icon Sets -->
    <link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet" />
    <link href="{% static 'css/boxicons.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/remixicon.css' %}" rel="stylesheet" />
    <link href="{% static 'css/quill.snow.css' %}" rel="stylesheet" />
    <link href="{% static 'css/quill.bubble.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/lateststyle.css' %}" />
    <!-- dataTable Responsive -->
    <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/responsive.dataTables.min.css' %}" />
  </head>

  <body>
    <header id="header" class="header fixed-top d-flex align-items-center">
      <div class="d-flex align-items-center justify-content-between">

        <i class="bi bi-list toggle-sidebar-btn"></i>
      </div>
      <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">
          <li class="nav-item d-block d-lg-none">
            <a class="nav-link nav-icon search-bar-toggle" href="#">
              <i class="bi bi-search"></i>
            </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
              <i class="bi bi-bell"></i>
              <span class="badge bg-primary badge-number">4</span>
            </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
              <i class="bi bi-chat-left-text"></i>
              <span class="badge bg-success badge-number">3</span>
            </a>
          </li>
          <li class="nav-item dropdown pe-3">
            <a
              class="nav-link nav-profile d-flex align-items-center pe-0"
              href="#"
              data-bs-toggle="dropdown"
            >
              <img
                src="{% static 'img/profile-img.jpg' %}"
                alt="Profile"
                class="rounded-circle"
              />
              <span class="d-none d-md-block dropdown-toggle ps-2">Jassa</span>
            </a>
            <ul
              class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile"
            >
              <li class="dropdown-header">
                <h6>Jassa</h6>
                <span>Admin Assistant</span>
              </li>
              <li>
                <hr class="dropdown-divider" />
              </li>
              <li>
                <a
                  class="dropdown-item d-flex align-items-center"
                  href="users-profile.html"
                >
                  <i class="bi bi-person"></i> <span>My Profile</span>
                </a>
              </li>
              <li>
                <hr class="dropdown-divider" />
              </li>
              <li>
                <a
                  class="dropdown-item d-flex align-items-center"
                  href="../profile/change-password.html"
                >
                  <i class="bi bi-eye"></i> <span>Change Password</span>
                </a>
              </li>
              <li>
                <hr class="dropdown-divider" />
              </li>
              <li>
                <a
                  class="dropdown-item d-flex align-items-center"
                  href="users-profile.html"
                >
                  <i class="bi bi-gear"></i> <span>Account Settings</span>
                </a>
              </li>
              <li>
                <hr class="dropdown-divider" />
              </li>
              <li>
                <a
                  class="dropdown-item d-flex align-items-center"
                  href="pages-faq.html"
                >
                  <i class="bi bi-question-circle"></i> <span>Need Help?</span>
                </a>
              </li>
              <li>
                <hr class="dropdown-divider" />
              </li>
              <li>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <i class="bi bi-box-arrow-right"></i> <span>Sign Out</span>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
    </header>
    <aside id="sidebar" class="sidebar">
      <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="bi bi-grid"></i> <span>Dashboard</span></a
          >
        </li>
        <!-- Masters nav-iems start here-->
        <li class="nav-item">
          <a
            class="nav-link collapsed"
            data-bs-target="#master-nav"
            data-bs-toggle="collapse"
            href="#"
          >
            <i class="bi bi-menu-button-wide"></i> <span>Master</span
            ><i class="bi bi-chevron-down ms-auto"></i>
          </a>

          <ul
            id="master-nav"
            class="nav-content collapse"
            data-bs-parent="#sidebar-nav"
          >

            <li>
              <a href="{% url 'department_list' %}">
                <i class="bi bi-circle"></i><span>Department</span>
              </a>
            </li>
            <li>
              <a href="{% url 'designation_list' %}">
                <i class="bi bi-circle"></i><span>Designation</span>
              </a>
            </li>

            <li>
              <a href="{% url 'location_list' %}">
                <i class="bi bi-circle"></i><span>Location</span>
              </a>
            </li>
          </ul>
        </li>
        <!-- Masters nav-iems ends here-->

        <!-- User -->

        <!-- ncr -->

        <!-- Callibration nav-item -->

      </ul>
    </aside>
    <main id="main" class="main">
      <div class="pagetitle">
        <h1>Edit Department Details</h1>
        <nav>
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="../index.html">Home</a></li>
            <li class="breadcrumb-item">Master</li>
            <li class="breadcrumb-item">
              <a href="{% url 'department_list' %}">Department</a>
            </li>
            <li class="breadcrumb-item active">Edit Department Details</li>
          </ol>
        </nav>
      </div>
      <section class="section">
        <div class="row">
          <div class="col-lg-12">
            <div class="card border border-primary p-4">
              <h5 class="card-heading">
                Edit The Details Of Department :
              </h5>
              <form method="post" action="{% url 'department_edit' department.pk %}">
                {% csrf_token %}
              <div class="row mb-3">
                <label for="id_department_name" class="col-md-4 col-lg-3 col-form-label">
                    Department Name <span class="text-danger">*</span>
                </label>
                <div class="col-md-8 col-lg-9">
                    <!-- Render the form field -->
                    <input type="text" class="form-control" name="department_name" id="id_department_name" value="{{ form.department_name.value }}" required>
                    
                </div>
            </div>
            
            <!-- Description -->
            <div class="row mb-3">
                <label for="id_description" class="col-md-4 col-lg-3 col-form-label">
                    Description <span class="text-danger">*</span>
                </label>
                <div class="col-md-8 col-lg-9">
                    <!-- Render the form field -->
                    <input type="text" class="form-control" name="description" id="id_description" value="{{ form.description.value }}" required>
                    
                </div>
            </div>
            
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary">Save Changes</button>
            </div>
        </form>
              
            </div>
          </div>
        </div>
        <div class="d-flex justify-content-center">
          <a href="{% url 'department_list' %}">
            <button class="btn btn-outline-success">
              <i class="bi bi-arrow-left-square me-1"></i>Back
            </button>
          </a>
        </div>
      </section>
      <div class="spacex mb-5"></div>
    </main>
    <footer id="footer" class="footer">
      <div class="copyright">
        &copy; Copyright <strong><span>Datahub Technologies</span></strong
        >. All Rights Reserved
      </div>
    </footer>
    <a
      href="#"
      class="back-to-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>
    <!-- Modal Start here -->
    <div
      class="modal fade"
      id="deleteModal"
      tabindex="-1"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>
          <!-- Replace this part with your well-crafted message -->
          <div class="modal-body">
            <p>Do you want to delete this item?</p>
          </div>
          <!-- End of message content -->
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              data-bs-dismiss="modal"
            >
              Close
            </button>
            <button type="button" class="btn btn-outline-danger">Delete</button>
          </div>
        </div>
      </div>
    </div>
    <!-- Modal ends here -->
    <script src="{% static 'js/apexcharts.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/chart.min.js' %}"></script>
    <script src="{% static 'js/echarts.min.js' %}"></script>
    <script src="{% static 'js/quill.min.js' %}"></script>
    <script src="{% static 'js/tinymce.min.js' %}"></script>
    <script src="{% static 'js/validate.js' %}"></script>
    <!-- Responsive DataTable start here -->
    <script src="{% static 'js/jquery-3.5.1.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.responsive.min.js' %}"></script>
    <!-- Responsive DataTable ends here -->
    <!-- init file start here -->
    <script src="{% static 'js/main.js' %}"></script>
    <!-- init file ends here -->
  </body>
</html>

templates/employee_view.html
<!DOCTYPE html>
{% extends 'index.html' %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
   
</head>
<body>
    <main id="main" class="main">
        <div class="pagetitle">
          <h1>Edit Employee</h1>
        </div>
        <section class="section">
          <div class="row">
            <div class="col-lg-12">
              <div class="card border border-primary p-4">
                <h5 class="card-heading">
                  Edit The Details Of Employee :
                </h5>
                <table class="table">
                    <tbody>
                      <tr>
                        <th scope="row" class="col-lg-4">
                          EMPLOYEE
                        </th>
                        <td class="col-lg-8"></td>
                      </tr>
                      <tr>
                        <th scope="row" class="col-lg-4">Join Date </th>
                        <td class="col-lg-8">{{ employee.join_date }}</td>
                      </tr>
                      <tr>
                        <th scope="row" class="col-lg-4">Employee Number</th>
                        <td class="col-lg-8">{{ employee.employee_no }}</td>
                      </tr>
                      <tr>
                        <th scope="row" class="col-lg-4">Name</th>
                        <td class="col-lg-8">{{ employee.name }}</td>
                      </tr>
                      <tr>
                        <th scope="row" class="col-lg-4">Phone</th>
                        <td class="col-lg-8">{{ employee.phone }}</td>
                      </tr>
                      <tr>
                        <th scope="row" class="col-lg-4">Address</th>
                        <td class="col-lg-8">{{ employee.address }}</td>
                      </tr>
                      <tr>
                        <th scope="row" class="col-lg-4">Emp Start Date</th>
                        <td class="col-lg-8">{{ employee.emp_start_date }}</td>
                      </tr>
                      <tr>
                        <th scope="row" class="col-lg-4">Emp End Date</th>
                        <td class="col-lg-8">{{ employee.emp_end_date }}</td>
                      </tr>
                      <tr>
                        <th scope="row" class="col-lg-4">Photo</th>
                        <td class="col-lg-8">
                          {% if employee.photo %}
                            <!-- Provide download link with appropriate file name -->
                            <a href="{{ employee.photo.url }}" download="{{ employee.photo.name }}" class="text-dark">
                            <i class="bi bi-file-earmark-image"></i> Download Photo
                            </a>
                          {% else %}
                            <!-- Message indicating no photo is available -->
                            No photo available
                          {% endif %}
                        </td>
                      </tr>
                      <tr>
                        <th scope="row" class="col-lg-4">Status</th>
                        <td class="col-lg-8">{{ employee.status }}</td>
                      </tr>
                      <tr>
                        <th scope="row" class="col-lg-4">Department</th>
                        <td class="col-lg-8">{{ department }}</td>
                      </tr>
                      <tr>
                        <th scope="row" class="col-lg-4">Designation</th>
                        <td class="col-lg-8">{{ designation }}</td>
                      </tr>
                      <tr>
                        <th scope="row" class="col-lg-4">Location</th>
                        <td class="col-lg-8">{{ location }}</td>
                      </tr>
                      <tr>
                        <th scope="row" class="col-lg-4">Skills</th>
                        <td class="col-lg-8">
                            
                                {% for skill in skills %}
                                <div>
                                    <strong>Skill Name:</strong> {{ skill.skill_name }}<br>
                                    <strong>Skill Description:</strong> {{ skill.description }}<br><br>
                                </div>
                                {% empty %}
                                    <p>No skills listed</p>
                                {% endfor %}
                            
                        </td>
                    </tr>

                      
                    </tbody>
                  </table>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-center">
            <a href="{% url 'employee_list' %}">
              <button class="btn btn-outline-success">
                <i class="bi bi-arrow-left-square me-1"></i>Back
              </button>
            </a>
          </div>
        </section>
        <div class="spacex mb-5"></div>
      </main>

      <script type="text/javascript">
        $(document).ready(function () {
            $('#id_join_date').datepicker({
                
                dateFormat: 'yy-mm-dd'
            });
            
           
        });
    </script>
    
  <script type="text/template" id="empty-form">
    <div class="skill-form">
        <input type="hidden" name="form-__prefix__-id" id="id_form-__prefix__-id">
        <div class="row mb-3">
            <label class="col-md-4 col-lg-3 col-form-label">Skill Name</label>
            <div class="col-md-8 col-lg-9">
                <input type="text" name="form-__prefix__-skill_name" class="form-control" required id="id_form-__prefix__-skill_name">
            </div>
        </div>
        <div class="row mb-3">
            <label class="col-md-4 col-lg-3 col-form-label">Skill Description</label>
            <div class="col-md-8 col-lg-9">
                <input type="text" name="form-__prefix__-description" class="form-control" required id="id_form-__prefix__-description">
            </div>
        </div>
    </div>
</script>
  
    
</body>
</html>
{% endblock %}

templates/profile_edit.html
<!DOCTYPE html>

{% extends 'index.html' %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
   
</head>

<body>
    <main id="main" class="main">
        <div class="pagetitle">
          <h1>Edit Profile</h1>
          <!-- <nav>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="../index.html">Home</a></li>
              <li class="breadcrumb-item">Master</li>
              <li class="breadcrumb-item">
                <a href="project-allocation.html">Project Allocation</a>
              </li>
              <li class="breadcrumb-item active">Add Project Allocation</li>
            </ol>
          </nav> -->
        </div>
        <section class="section">
          <div class="row">
            <div class="col-lg-12">
              <div class="card border border-primary p-4">
                <h5 class="card-heading">
                  Edit The Details :
                </h5>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row mb-3">
                        <label for="username"
                          class="col-md-4 col-lg-3 col-form-label">Username<span class="text-danger">*</span></label>
                       
                        <div class="col-md-8 col-lg-9">
                            {{ form.username }}
                            {{ form.username.errors }}
                        </div>
                      </div>
                      <div class="row mb-3">
                        <label for="first_name"
                          class="col-md-4 col-lg-3 col-form-label">first_name<span class="text-danger">*</span></label>
                       
                        <div class="col-md-8 col-lg-9">
                            {{ form.first_name }}
                            {{ form.first_name.errors }}
                        </div>
                      </div>
                      <div class="row mb-3">
                        <label for="last_name"
                          class="col-md-4 col-lg-3 col-form-label">last_name<span class="text-danger">*</span></label>
                       
                        <div class="col-md-8 col-lg-9">
                            {{ form.last_name }}
                            {{ form.last_name.errors }}
                        </div>
                      </div>
                      <div class="row mb-3">
                        <label for="email"
                          class="col-md-4 col-lg-3 col-form-label">email<span class="text-danger">*</span></label>
                       
                        <div class="col-md-8 col-lg-9">
                            {{ form.email }}
                            {{ form.email.errors }}
                        </div>
                      </div>
                    
                      <div class="row mb-3">
                        <label for="role"
                          class="col-md-4 col-lg-3 col-form-label">role<span class="text-danger">*</span></label>
                       
                        <div class="col-md-8 col-lg-9">
                            {{ form.role }}
                            {{ form.role.errors }}
                        </div>
                      </div>
                     
                     
                    <button type="submit" class= "btn btn-primary" style="display: block; margin: 0 auto;">Save</button>

                </form>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-center">
            <a href="{% url 'indexpage' %}">
              <button class="btn btn-outline-success">
                <i class="bi bi-arrow-left-square me-1"></i>Back
              </button>
            </a>
          </div>
        </section>
        <div class="spacex mb-5"></div>
      </main>

    
</body>
</html>
{% endblock %}